Create README.md
pelican-eggs/software pull request #12
Opened 2024-12-27 20:36 UTC by devilAPI

# Description

## Checklist for all submissions

* [X ] Have you followed the guidelines in our [Contributing document](https://github.com/parkervcp/eggs/blob/master/CONTRIBUTING.md)?
* [X ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
* [X ] Have you tested and reviewed your changes with confidence that everything works?
* [ ] Did you branch your changes and PR from that branch and not from your master branch?
  * If not, why?:

* [ ] You verify that the start command applied does not use a shell script
  * [ ] If some script is needed then it is part of a current yolk or a PR to add one
* [ ] The egg was exported from the panel

## New egg Submissions

1. [X ] Does your submission pass tests (server is connectable)?
2. [X ] Does your egg use a custom docker image? 
    * [X ] Have you tried to use a generic image? 
    * [?] Did you PR the necessary changes to make it work?
3. [X ] Have you added the egg to the main README.md and any other README files in subdirectories of the egg (e.g /game_eggs) according to the alphabetical order?
4. [X] Have you added a unique README.md for the egg you are adding according to the alphabetical order?
5. [X] You verify that the start command applied does not use a shell script
    * [ ] If some script is needed then it is part of a current yolk or a PR to add one
6. [X ] The egg was exported from the panel

2024-12-27 21:31 UTC, QuintenQVD0 requested changes

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/egg-navidrome.json
> +        "devilapi\/navidrome-pterodactyl:latest": "devilapi\/navidrome-pterodactyl:latest"
This is not allowed. The image must be owned by pelican. So please pr it if it meeds the requirements

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/egg-navidrome.json
> +    "file_denylist": [],
Startup script is also not allowed for security reasons.

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/egg-navidrome.json
> +            "script": "mkdir \/mnt\/server\/music",
Based on this I assume the files are in the image. This is not allowed. The install script should download them. The image should only hold pacakges.

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/egg-navidrome.json
> +            "user_viewable": true,
If this the only needed port then please use the build in SERVER_PORT var

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/README.md
> +[GitHub Repository](https://github.com/devilAPI/navidrome-music-streaming-pterodactyl-egg).
This should link to the software source. Not where you host your egg.

2024-12-27 21:31 UTC, QuintenQVD0 commented on navidrome/README.md
> +Just import it into Pterodactyl, change the "Port" value on the "Startup" page and you're good to go!
Where is the required ports table?

2024-12-27 21:33 UTC, QuintenQVD0 commented
Where even is the source code for this bot?

2024-12-27 21:41 UTC, devilAPI commented
> Contributor

its not a bot, its a subsonic server, something like selfhosted spotify.

https://github.com/navidrome/navidrome/tree/master

2024-12-28 09:21 UTC, QuintenQVD0 commented
> > Contributor
> 
> its not a bot, its a subsonic server, something like selfhosted spotify.
> 
> https://github.com/navidrome/navidrome/tree/master

Thats fine but please read https://github.com/pelican-eggs/software/blob/main/CONTRIBUTING.md and resolve all my comments please

2025-09-26 17:22 UTC, gOOvER commented
since a long time no answer and no resolve: -> closed

2025-09-26 17:22 UTC, closed without merging